export enum ConfigName {
  APP = 'app',
  CONTROLLER = 'controller',
  DATABASE = 'database',
  DESTINATION_DATABASE = 'destination-database',
  BROKER = 'broker',
  ORCHESTRATOR = 'orchestrator',
  REDIS = 'redis',
  SERVICES = 'services',
  STORAGE = 'storage',
  PROCESSOR = 'processor',
  WEBHOOK = 'webhook',
  MICROSOFT = 'microsoft',
  GOOGLE = 'google',
}
