export type ErrorCode = number;

export const ERROR_CODE = {
  VALIDATION_FAILED: 400,

  TOKEN_MISSING_PERMISSIONS: 1001,
  TOKEN_INVALID: 1002,
  TOKEN_EXPIRED: 1003,

  SPREADSHEET_NOT_FOUND: 2001,
  SPREADSHEET_MISSING_PERMISSIONS: 2002,

  GOOGLE_DRIVE_FILE_NOT_FOUND: 3001,
  GOOGLE_DRIVE_FILE_MISSING_PERMISSIONS: 3002,
};
