export const InjectTokens = {
  BROKER_CLIENT: 'BROKER_CLIENT',

  ORCHESTRATOR_CONNECTION_CONFIG: 'ORCHESTRATOR_CONNECTION_CONFIG',
  ORCHESTRATOR_NATIVE_CONNECTION_CONFIG:
    'ORCHESTRATOR_NATIVE_CONNECTION_CONFIG',
  ORCHESTRATOR_CONNECTION: 'ORCHESTRATOR_CONNECTION',
  ORCHESTRATOR_NATIVE_CONNECTION: 'ORCHESTRATOR_NATIVE_CONNECTION',
  ORCHESTRATOR_CLIENT: 'ORCHESTRATOR_CLIENT',

  DATA_PROVIDER_REPOSITORY: 'DATA_PROVIDER_REPOSITORY',
  DATA_SOURCE_REPOSITORY: 'DATA_SOURCE_REPOSITORY',
  SYNC_CONNECTION_REPOSITORY: 'SYNC_CONNECTION_REPOSITORY',
  SYNCFLOW_REPOSITORY: 'SYNCFLOW_REPOSITORY',
  TRIGGER_REPOSITORY: 'TRIGGER_REPOSITORY',
  WEBHOOK_REPOSITORY: 'WEBHOOK_REPOSITORY',

  MICROSOFT_AUTH_CLIENT: 'MICROSOFT_AUTH_CLIENT',
};
