steps:
  - id: 'Starion Sync Deploy Image'
    name: ${_DEPLOY_IMAGE_URL}
    dir: infra/staging
    entrypoint: 'bash'
    args:
      - '-c'
      - |-
        gcloud -h
        docker -v
  - id: 'tf init'
    name: 'hashicorp/terraform:1.6.1'
    dir: infra/staging
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        cd terraform
        terraform fmt -check
        terraform init -backend-config=gcs.tfbackend

substitutions:
  # _DEPLOY_IMAGE_URL: gcr.io/${PROJECT_ID}/starion-sync-deploy
  _DEPLOY_IMAGE_URL: ''
timeout: 1800s
options:
  machine_type: UNSPECIFIED
  dynamic_substitutions: true
  substitution_option: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
